

name: version-file-test


on:

  push:
    branches: [ add-node-version-file-support ]
  pull_request:
    branches: [ add-node-version-file-support ]


  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

  
    steps:
      
      - uses: actions/checkout@v2
      - name: Setup node test
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build
